# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import authentication_pb2 as authentication__pb2


class AuthenticationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.makelogin = channel.unary_unary(
        '/Authentication/makelogin',
        request_serializer=authentication__pb2.Login.SerializeToString,
        response_deserializer=authentication__pb2.Answer.FromString,
        )
    self.authorize_vehicle = channel.unary_unary(
        '/Authentication/authorize_vehicle',
        request_serializer=authentication__pb2.Authorize.SerializeToString,
        response_deserializer=authentication__pb2.Answer.FromString,
        )
    self.user_finish = channel.unary_unary(
        '/Authentication/user_finish',
        request_serializer=authentication__pb2.Finish.SerializeToString,
        response_deserializer=authentication__pb2.Answer.FromString,
        )


class AuthenticationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def makelogin(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def authorize_vehicle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def user_finish(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthenticationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'makelogin': grpc.unary_unary_rpc_method_handler(
          servicer.makelogin,
          request_deserializer=authentication__pb2.Login.FromString,
          response_serializer=authentication__pb2.Answer.SerializeToString,
      ),
      'authorize_vehicle': grpc.unary_unary_rpc_method_handler(
          servicer.authorize_vehicle,
          request_deserializer=authentication__pb2.Authorize.FromString,
          response_serializer=authentication__pb2.Answer.SerializeToString,
      ),
      'user_finish': grpc.unary_unary_rpc_method_handler(
          servicer.user_finish,
          request_deserializer=authentication__pb2.Finish.FromString,
          response_serializer=authentication__pb2.Answer.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Authentication', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
